log:
  level: error
  file: "/tmp/mosdns.log"

api:
  http: "0.0.0.0:9099"

include: []

plugins:
#列表外域名访问记录
#列表外域名访问记录
  - tag: my_notinlist
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/notinlist.txt
      file_rule: /etc/mosdns/gen/notinrule.txt
      max_entries: 20
      dump_interval: 36000

#访问过的realip的域名清单和生成规则
  - tag: my_realiplist
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/realiplist.txt
      file_rule: /etc/mosdns/gen/realiprule.txt
      max_entries: 2000
      dump_interval: 36005

#访问过的fakeip的域名清单和生成规则
  - tag: my_fakeiplist
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/fakeiplist.txt
      file_rule: /etc/mosdns/gen/fakeiprule.txt
      max_entries: 2000
      dump_interval: 36010

#访问过的无v6 ip的域名清单和生成规则
  - tag: my_nov6list
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/nov6list.txt
      file_rule: /etc/mosdns/gen/nov6rule.txt
      max_entries: 10
      dump_interval: 36020

#访问过的无v4 v6 ip的域名清单和生成规则
  - tag: my_nov4list
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/nov4list.txt
      file_rule: /etc/mosdns/gen/nov4rule.txt
      max_entries: 3
      dump_interval: 36030

#节点域名无v6 ip的域名清单和生成规则
  - tag: my_nodenov6list
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/nodenov6list.txt
      file_rule: /etc/mosdns/gen/nodenov6rule.txt
      max_entries: 1000
      dump_interval: 36070

#节点域名无v4 v6 ip的域名清单和生成规则
  - tag: my_nodenov4list
    type: domain_output
    args:
      file_stat: /etc/mosdns/gen/nodenov4list.txt
      file_rule: /etc/mosdns/gen/nodenov4rule.txt
      max_entries: 2
      dump_interval: 36080

#生成的realip规则
  - tag: my_realiprule
    type: domain_set
    args:
      files:
        - "/etc/mosdns/gen/realiprule.txt"

#生成的fakeip规则
  - tag: my_fakeiprule
    type: domain_set
    args:
      files:
        - "/etc/mosdns/gen/fakeiprule.txt"

#生成的没有v6的域名规则
  - tag: my_nov6rule
    type: domain_set
    args:
      files:
        - "/etc/mosdns/gen/nov6rule.txt"

#生成的没有ip的域名规则
  - tag: my_nov4rule
    type: domain_set
    args:
      files:
        - "/etc/mosdns/gen/nov4rule.txt"

#生成的节点没有v6的域名规则
  - tag: my_nodenov6rule
    type: domain_set
    args:
      files:
        - "/etc/mosdns/gen/nodenov6rule.txt"

#生成的节点没有ip的域名规则
  - tag: my_nodenov4rule
    type: domain_set
    args:
      files:
        - "/etc/mosdns/gen/nodenov4rule.txt"

#过期缓存
  - tag: cache_all
    type: cache
    args:
      size: 20000000
      lazy_cache_ttl: 259200000
      dump_file: /etc/mosdns/cache_all.dump
      dump_interval: 36000

#中国域名列表的过期缓存
  - tag: cache_cn
    type: cache
    args:
      size: 20000000
      lazy_cache_ttl: 259200000
      dump_file: /etc/mosdns/cache_cn.dump
      dump_interval: 36000

#列表外域名的过期缓存
  - tag: cache_google
    type: cache
    args:
      size: 20000000
      lazy_cache_ttl: 259200000
      dump_file: /etc/mosdns/cache_google.dump
      dump_interval: 36000

#节点域名列表的过期缓存
  - tag: cache_cf
    type: cache
    args:
      size: 20000000
      lazy_cache_ttl: 259200000
      dump_file: /etc/mosdns/cache_cf.dump
      dump_interval: 36000

#节点域名列表的过期缓存
  - tag: cache_node
    type: cache
    args:
      size: 20000000
      lazy_cache_ttl: 259200000
      dump_file: /etc/mosdns/cache_node.dump
      dump_interval: 36000

#中国域名列表
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/unpack/geosite_cn.txt"

#中国IP列表
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/etc/mosdns/unpack/geoip_cn.txt"

#国外域名列表
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/unpack/geosite_geolocation-!cn.txt"

#自定义白名单域名列表
  - tag: whitelist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/whitelist.txt"

#屏蔽域名列表
  - tag: blocklist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklist.txt"

#屏蔽V4解析的域名列表
  - tag: blocklistv4
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklistv4.txt"

#屏蔽V6解析的域名列表
  - tag: blocklistv6
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklistv6.txt"

#国外dns解析realip域名列表
  - tag: realiplist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/realiplist.txt"

#自定义强制代理域名列表
  - tag: greylist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"

#自定义hosts域名列表
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

#转发dns请求到google dns
  - tag: forward_google
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://8.8.8.8/dns-query"
        #  socks5: "127.0.0.1:7891"

#转发dns请求到cf dns
  - tag: forward_cf
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://1.1.1.1/dns-query"
       #   socks5: "127.0.0.1:7891"

#转发请求到阿里dns
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "223.5.5.5"
        - addr: "quic://223.5.5.5"
        - addr: "202.102.128.68"
          upstream_query_timeout: 10

#转发请求至sing-box/mihome dns请求fakeip
  - tag: forward_fakeip
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: 10.10.10.147:6666
          idle_timeout: 720

#转发国内请求到内部带过期缓存的服务
  - tag: forward_local_in
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:2222"

#国内域名 内部使用
  - tag: sequence_local_in
    type: sequence
    args:
      - exec: $cache_cn
      - matches: has_resp
        exec: accept
      - exec: $forward_local

#转发国外请求到内部带过期缓存的服务
  - tag: forward_google_in
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:3333"

#国外域名 内部使用
  - tag: sequence_google_in
    type: sequence
    args:
      - exec: $cache_google
      - matches: has_resp
        exec: accept
      - exec: ecs 2408:8214:213::1  #使用自己的公网IP，无须更新
      - exec: $forward_google

#转发国外请求到内部带过期缓存的服务
  - tag: forward_cf_in
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:4444"

#国外域名 内部使用
  - tag: sequence_cf_in
    type: sequence
    args:
      - exec: $cache_cf
      - matches: has_resp
        exec: accept
      - exec: $forward_cf

#缓存序列-国内域名
  - tag: sequence_local
    type: sequence
    args:
      - exec: drop_resp      #丢弃用于标记的blackhole ip
      - exec: $forward_local_in

#缓存序列-国内域名
  - tag: sequence_fakeip
    type: sequence
    args:
      - exec: drop_resp      #丢弃用于标记的blackhole ip
      - exec: $forward_fakeip

#缓存序列-列表外域名
  - tag: sequence_google
    type: sequence
    args:
      - exec: drop_resp      #丢弃用于标记的blackhole ip
      - exec: $forward_google_in

#缓存序列-列表外域名
  - tag: sequence_cf
    type: sequence
    args:
      - exec: drop_resp      #丢弃用于标记的blackhole ip
      - exec: $forward_cf_in

#转发国外请求到内部带过期缓存的服务
  - tag: forward_all_in
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:5656"

#缓存序列-all
  - tag: sequence_all
    type: sequence
    args:
      - matches: "qtype 6 12 65"
        exec: reject 0
      - exec: $cache_all
      - matches: has_resp
        exec: accept
      - exec: $forward_all_in

#列表外的域名的处理逻辑
#先带ecs到8888，如果返回235，就用cf再查一次，如果还返回235
#25的情况用223再查，3的情况返回no error
  - tag: sequence_not_in_list
    type: sequence
    args:
      - matches: "resp_ip 127.0.0.3 ::3"
        exec: $my_notinlist     
      - exec: drop_resp      #丢弃用于标记的blackhole ip  
      - exec: $sequence_google #表外域名先带ecs发到8888
      - matches: "!resp_ip 0.0.0.0/0 2000::/3"   #rcode 235及没有IP等情况
        exec: mark 123 #标记
      - matches: mark 123
        exec: drop_resp      #丢弃结果
      - matches: mark 123
        exec: $sequence_cf      #cf dns再查一次
      - matches: "rcode 3"   #失败或者拒绝
        exec: ttl 60000
      - matches:
        - "qtype 28"
        - "rcode 3"
        - "!cname keyword:."
        exec: $my_nov6list  #生成域名规则
      - matches:
        - "qtype 1"
        - "rcode 3"
        - "!cname keyword:."
        exec: $my_nov4list  #生成域名规则
      - matches: "rcode 3"   #没有域名
        exec: accept
      - matches: "rcode 2 5"   #失败或者拒绝
        exec: mark 456 #失败拒绝标记
      - matches: mark 456
        exec: drop_resp      #丢弃结果
      - matches: mark 456  #只有rcode 2 5需要到国内查询，rcode3 会接受结果
        exec: $sequence_local      #SERVFAIL用国内dns再查一次
      - matches:
        - "qtype 28"
        - "rcode 2 3 5"
        - "!resp_ip 2000::/3"
        exec: $my_nov6list  #生成域名规则
      - matches:
        - "qtype 1"
        - "rcode 2 3 5"
        - "!resp_ip 0.0.0.0/0"
        exec: $my_nov4list  #生成域名规则
      - matches: "rcode 2 3 5"   #失败或者拒绝
        exec: accept                      #实在没有ip就接受
      - matches: "!resp_ip 0.0.0.0/0 2000::/3"
        exec: accept                      #再没有IP返回就把结果返回给客户端
      - matches: "resp_ip 17.0.0.0/8"
        exec: $my_realiplist  #生成域名规则
      - matches: "resp_ip 17.0.0.0/8"
        exec: accept                      #苹果ip就接受
      - matches: "!resp_ip $geoip_cn"
        exec: mark 89 #标记
      - matches: mark 89
        exec: $sequence_fakeip
      - matches: mark 89
        exec: $my_fakeiplist
      - exec: accept

#生成的规则用本地dns查询
  - tag: gen_is_local_dns
    type: sequence
    args:
      - matches: qname $my_realiprule
        exec: black_hole 127.0.0.1 ::1

#生成的规则请求fakeip
  - tag: gen_is_fakeip
    type: sequence
    args:
      - matches: qname $my_fakeiprule
        exec: black_hole 127.0.0.2 ::2
      - matches: "!resp_ip 127.0.0.2 ::2"
        exec: black_hole 127.0.0.3 ::3

#生成的列表国内国外并发匹配，结果是black_hole的即列表外域名
  - tag: gen_conc
    type: fallback
    args:
      primary: gen_is_local_dns
      secondary: gen_is_fakeip
      threshold: 1
      always_standby: true

#用本地dns查询
  - tag: query_is_local_dns
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: black_hole 127.0.0.1 ::1

#fallback并发primary和secondary都没有IP返回，会抛出错误
#导致后续逻辑无法执行，在secondary中使用black_hole给假
#ip作为标记供后续判断

#国外域名列表/灰名单直接请求fakeip
  - tag: query_is_fakeip
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: black_hole 127.0.0.2 ::2
      - matches: "!resp_ip 127.0.0.2 ::2"
        exec: black_hole 127.0.0.3 ::3

#列表内域名国内国外并发匹配，结果是black_hole的即列表外域名
  - tag: conc_lookup
    type: fallback
    args:
      primary: query_is_local_dns
      secondary: query_is_fakeip
      threshold: 1
      always_standby: true

#主分流序列
  - tag: sequence_main
    type: sequence
    args:
      - matches: qname $blocklist
        exec: reject 3
      - exec: $hosts
      - matches: has_resp
        exec: accept
      - matches: "!qtype 1 28"
        exec: $sequence_google
      - matches: "!qtype 1 28"
        exec: accept
      - matches: qname $greylist
        exec: mark 22
      - matches: mark 22
        exec: $sequence_fakeip
      - matches: mark 22
        exec: accept
      - matches:    #屏蔽没有v4地址的域名
        - qtype 1
        - qname $my_nov4rule
        exec: reject 0
      - matches:    #屏蔽没有v6地址的域名
        - qtype 28
        - qname $my_nov6rule
        exec: reject 0
      - matches: qname $whitelist
        exec: mark 11
      - matches: mark 11
        exec: $sequence_local
      - matches:
        - "mark 11"
        - "rcode 0 2 3 5"
        - "!resp_ip 0.0.0.0/0 2000::/3"
        exec: ttl 60000 #非A没有IP，延长TTL
      - matches:
        - "qtype 28"  
        - "mark 11"
        - "rcode 0 2 3 5"
        - "!resp_ip 2000::/3"
        - "!cname keyword:."
        exec: $my_nov6list  #生成域名规则
      - matches:
        - "qtype 1"  
        - "mark 11"
        - "rcode 0 2 3 5"
        - "!resp_ip 0.0.0.0/0"
        - "!cname keyword:."
        exec: $my_nov4list  #生成域名规则
      - matches: mark 11  #白名单中域名不往下漏
        exec: accept
      - matches: qname $realiplist
        exec: mark 33
      - matches: mark 33
        exec: $sequence_google
      - matches: mark 33
        exec: accept
      - exec: $gen_conc
      - matches: "resp_ip 127.0.0.1 ::1"
        exec: mark 888 #生成的域名列表匹配为realip
      - matches: "resp_ip 127.0.0.2 ::2"
        exec: mark 999 #生成的域名列表匹配为realip
      - matches: "resp_ip 127.0.0.3 ::3"
        exec: mark 666 #标记
      - matches: mark 666
        exec: drop_resp      #丢弃结果
      - matches: mark 666
        exec: $conc_lookup
      - matches: "resp_ip 127.0.0.1 ::1"
        exec: $sequence_local
      - matches: "resp_ip 127.0.0.2 ::2"
        exec: mark 777 #标记
      - matches: mark 777
        exec: $sequence_fakeip
      - matches:
        - "mark 777"  #fakeip
        - "!mark 999" #并没有在gen fakeip列表中
        exec: $my_fakeiplist  #生成域名规则
      - matches: mark 777
        exec: accept                      #fakeip就接受
      - matches:
        - "!mark 888" #并没有在gen realip列表中
        - "resp_ip 17.0.0.0/8"  #fakeip
        exec: $my_realiplist  #生成域名规则
      - matches: "resp_ip 17.0.0.0/8"
        exec: accept                      #fakeip ios ip就接受
      - matches:
        - "qtype 28"  #非A的只要不是黑洞IP，有没有IP都接受
        - "rcode 0 2 3 5"
        - "!resp_ip 2000::/3"
        - "!resp_ip ::1 ::2 ::3"
        exec: ttl 60000 #非A没有IP，延长TTL
      - matches:
        - "qtype 28"  #非A的只要不是黑洞IP，有没有IP都接受
        - "rcode 0 2 3 5"
        - "!resp_ip 2000::/3"
        - "!resp_ip ::1 ::2 ::3"
        - "!cname keyword:."
        exec: $my_nov6list  #生成域名规则
      - matches:
        - "qtype 28"  #非A的有realip的情况
        - "!mark 888" #并没有在gen realip列表中
        - "resp_ip 2000::/3"
        - "!resp_ip ::1 ::2 ::3"
        exec: $my_realiplist  #生成域名规则
      - matches:
        - "qtype 28"  #非A的只要不是黑洞IP，有没有IP都接受
        - "!resp_ip ::1 ::2 ::3"
        exec: accept
      - matches:
        - "qtype 1"  #A的不是黑洞IP，有正经IP才接受
        - "!mark 888" #并没有在gen realip列表中
        - "resp_ip 0.0.0.0/0"
        - "!resp_ip 0.0.0.0 127.0.0.1 127.0.0.2 127.0.0.3"
        exec: $my_realiplist  #生成域名规则
      - matches:
        - "qtype 1"  #A的不是黑洞IP或者污染ip，有正经IP才接受
        - "resp_ip 0.0.0.0/0"
        - "!resp_ip 0.0.0.0 127.0.0.1 127.0.0.2 127.0.0.3"
        exec: accept
      - exec: $sequence_not_in_list  #其它走表外逻辑
      - exec: accept

#处理列表外域名的缓存序列
  - tag: sbnodefallback
    type: fallback
    args:
      primary: sequence_google
      secondary: sequence_local
      threshold: 5
      always_standby: false

  - tag: sequence_sbnode
    type: sequence
    args:
      - matches:    #屏蔽没有v4地址的域名
        - qtype 1
        - qname $my_nodenov4rule
        exec: reject 0
      - matches:    #屏蔽没有v6地址的域名
        - qtype 28
        - qname $my_nodenov6rule
        exec: reject 0
      - exec: $cache_node
      - matches: has_resp
        exec: accept
      - exec: sleep 1000
      - exec: $sbnodefallback
      - matches:
        - "qtype 1" 
        - "rcode 0 2 3 5"
        - "!resp_ip 0.0.0.0/0"
        - "!cname keyword:."
        exec: $my_nodenov4list  #生成域名规则
      - matches:
        - "qtype 28" 
        - "rcode 0 2 3 5"
        - "!resp_ip 2000::/3"
        - "!cname keyword:."
        exec: $my_nodenov6list  #生成域名规则

####################对外服务端口定义部分############
#解析节点域名的服务器
  - tag: sbnode_udp
    type: udp_server
    args:
      entry: sequence_sbnode
      listen: ":7777"

  - tag: sbnode_tcp
    type: tcp_server
    args:
      entry: sequence_sbnode
      listen: ":7777"

#sing-box使用的服务器
  - tag: sb_udp
    type: udp_server
    args:
      entry: sequence_local
      listen: ":8888"

  - tag: sb_tcp
    type: tcp_server
    args:
      entry: sequence_local
      listen: ":8888"

#国内
  - tag: udp_local
    type: udp_server
    args:
      entry: sequence_local_in
      listen: ":2222"

  - tag: tcp_local
    type: tcp_server
    args:
      entry: sequence_local_in
      listen: ":2222"

#国外
  - tag: udp_google
    type: udp_server
    args:
      entry: sequence_google_in
      listen: ":3333"

  - tag: tcp_google
    type: tcp_server
    args:
      entry: sequence_google_in
      listen: ":3333"
#国外
  - tag: udp_cf
    type: udp_server
    args:
      entry: sequence_cf_in
      listen: ":4444"

  - tag: tcp_cf
    type: tcp_server
    args:
      entry: sequence_cf_in
      listen: ":4444"

#主分流服务器
  - tag: udp_main
    type: udp_server
    args:
      entry: sequence_main
      listen: ":5656"

  - tag: tcp_main
    type: tcp_server
    args:
      entry: sequence_main
      listen: ":5656"
      idle_timeout: 720

#对外服务器
  - tag: udp_all
    type: udp_server
    args:
      entry: sequence_all
      listen: ":53"

  - tag: tcp_all
    type: tcp_server
    args:
      entry: sequence_all
      listen: ":53"
      idle_timeout: 720